### PR TITLE
Travis cleanup

### PR DESCRIPTION
**Pull request by bsipocz**
This should ultimately address both #3 and #6, but there are still upstream issues. Opening it now as a WIP, so less likely it slips out of my mind.

### CODE REVIEW

**Comment by bsipocz** [comment]
Btw a nice workaround for the pip install issues would be to update the conda-forge build for healpy to get the latest version (rather than 1.9.1). That case it would be built with newer numpies...

**Comment by bsipocz** [comment]
Actually I have no idea why the egg_build disappears. It does the same thing when I build the latest hips master on my fork, too (https://travis-ci.org/bsipocz/hips/builds/237675420)

**Comment by cdeil** [comment]
@bsipocz - Can you please leave the Appveyor build in place? At the moment we don't import healpy yet, so it should be possible.

I think we definitely want to support Windows here, this is a package that many hobby astronomers or schools might like: an easy way to fetch images and catalogs for any part of the sky, and expose it in a form so that it can be analysed with Python.

The functionality we need from healpy here is very limited, and if they don't start supporting Windows soon, I might actually take the time and implement https://github.com/cdeil/healpix and then we use that here instead of healpy.

**Comment by bsipocz** [comment]
OK, fair enough. To be honest I only checked the installation docs to see whether it's a requirement or an optional one.

**Comment by bsipocz** [comment]
(close-reopen: just pushed a fix to ``ci-helpers``, and needed to retrigger travis on this PR)

**Comment by bsipocz** [comment]
@cdeil - This should be good to go for travis, there's one docs warning left only, I haven't paid much attention to appveyor. Also you may want to opt in the auto cancellation on travis, so outdated commits get cancelled out of the queue.

**Comment by cdeil** [comment]
@bsipocz - https://travis-ci.org/hipspy/hips/jobs/238045310#L1023 ?

For https://travis-ci.org/hipspy/hips/jobs/238045306#L1083 , can you just add this to the toc in `index.rst` or should I do that in master?

**Comment by cdeil** [comment]
I didn't know about travis-ci auto-cancel. Thanks!
I've activated it for this `hips` repo and `gammapy` as well.

**Comment by bsipocz** [comment]
@cdeil - Yes, they have it for about 6 months now, and just moved it out from beta testing this week. In astropy we use it since early beta times, works quite well.

**Comment by bsipocz** [comment]
Also I can do the toc fix tomorrow.

**Comment by cdeil** [comment]
> also I guess you don't want to deal with astropy 1.0.x compatibility?

No. Even just supporting Astropy 1.3 or later for this package would be fine.

**Comment by bsipocz** [comment]
@cdeil - This should be ready now and get a green travis.

**Comment by cdeil** [comment]
🎉

**Pull request merged**
