### PR TITLE
Set up initial Python package

### PR DESCRIPTION
**Pull request by cdeil**
I would like to set up this Python package in the coming days.

After looking around a bit for Python project templates, my recommendation would be that we use the `package-template` from the Astropy folks.

It has a lot of boilerplate stuff, even an astropy-helpers git submodule, which in principle I don't like.

But it also gives a lot of things (versioning, docs, robust cython / c extension build if we need it later, config for continuous integration via travis-ci and appveyor and for hosting / build on readthedocs) within minutes, instead of spending a day to set it all up correctly.

Since a few days, they have a cookiecutter version to scaffold it out quickly.
See https://github.com/astropy/package-template/issues/230 for my first attempt.

The most important advantage of using the Astropy package template is that many Astropy Python developers know it and will be able to quickly find their way around the hips package and start contributing or helping out if there's an issue.

@tboch - OK to go this way? Or do you prefer something else?

### CODE REVIEW

**Comment by cdeil** [comment]
@tboch @adl1995 - I've added the files from the Astropy affiliated package-template here, and adapted them a bit (added some docs, removed Python 2 builds from continuous integration, ...).

I'm merging this now, and will try to set up travis-ci, Appveyor and Readthedocs and register the package name on PyPI. Of course, if you have any issues or would like something changed, this is not set in stone, open an issue or pull request any time!

**Comment by cdeil** [comment]
@tboch - Apparently I can't activate travis-ci for this repo? Or at least it doesn't appear in the auto-discovery list of packages I can activate. Can you make me a co-owner of hipspy? That would also give me permissions to label and merge pull requests for the hips-extra repo.

Also -- can you let me know of your username on PyPI and Readthedocs, so that I can give you permissions there?

**Comment by cdeil** [comment]
This worked:
```
python setup.py sdist
twine register dist/hips-0.0.dev8.tar.gz 
```
So we now have the package "registered" (i.e. name reserved, no release made yet) on PyPI: https://pypi.python.org/pypi/hips

**Comment by cdeil** [comment]
I've activated travis-ci and readthedocs at https://github.com/hipspy/hips/settings/installations

For readthedocs, I'm trying to get the conda-based build to work: https://readthedocs.org/projects/hips/

For travis-ci, there's still no builds happening (see https://travis-ci.org/hipspy/hips) and I apparently don't have permissions to add this repo there. @tboch - Can you do it please, or add me to the hipspy organisation, I think then I should have permissions to do this?

**Comment by tboch** [comment]
@cdeil - I've sent an invitation to make you owner of the hipspy org. Let me know if that works

**Comment by cdeil** [comment]
@tboch - Thanks!

I'll try getting travis-ci running now.

For me, I've changed at https://github.com/orgs/hipspy/people from private to public. This means that others can see that I'm part of `hipspy`. For you it's still set to "private". Maybe change to "public" so that if someone is interested in this project, they know to contact you?

**Comment by cdeil** [comment]
First travis-ci build is running:
https://travis-ci.org/hipspy/hips/builds/236887747

**Comment by tboch** [comment]
ok, I've changed my own visibility on https://github.com/orgs/hipspy/people to public as well

**Comment by cdeil** [comment]
First docs build that passed on readthedocs:
https://readthedocs.org/projects/hips/builds/5483522/

We're live: http://hips.readthedocs.io/en/latest/

**Pull request merged**
