### PR TITLE
Sphinx update

### PR DESCRIPTION
**Pull request by adl1995**
I used `git reset --soft HEAD~12` to merge the previous 12 commits. Only the `index.rst` file is updated in this pull request.

### CODE REVIEW

**Comment by cdeil** [comment]
Diff looks good.

There's still a merge commit here that's not really nice:
https://github.com/hipspy/hips/pull/13/commits

Do you want to try and get rid of it? Or should I merge now?

**Comment by adl1995** [comment]
Apparently I had to delete the branch as Git wouldn't allow me to push after squashing previous commits as it was a commit behind the remote branch.

**Comment by cdeil** [comment]
You always have to use `git put -f` (force push) after you change commits locally (e.g. with `git rebase` or `git reset`), i.e. every time the push "destroys" commits on the server. That's normal, I do it every day when I rebase my commits and clean up my git commit history for a given pull request, before merging it. But you have to be careful / know what you're doing, because `git rebase`, `git reset` and `git push -f` have the potential to really loose edits / commits if you screw up.

**Comment by adl1995** [comment]
Thanks!

I now have two commits, namely "Merge branch 'master' of https://github.com/hipspy/hips into sphinx-update" and "Shpinx docs update" and I wish to merge them into a single commit.

I'm following [this](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git/5201642#5201642) SO answer and issuing this command `git reset --soft HEAD~2`, but when I do this the pull from master is lost. Is there any alternative way for merging together 2 commits?

**Comment by cdeil** [comment]
I'm usually using `git rebase -i master` to rebase against the latest master and clean up my commit history for a given branch. Can you try that?

**Pull request closed without merging**
